<?php

use App\Enums\UserRole;

return [
    'abilities' => [
        'view_software',
        'create_software',
        'edit_software',
        'delete_software',
        'manage_dependencies',
        'view_versions',
        'create_versions',
        'edit_versions',
        'delete_versions',
        'approve_versions',
        'publish_versions',
        'override_release_readiness',
        'view_content',
        'create_content',
        'edit_content',
        'delete_content',
        'upload_files',
        'edit_files',
        'delete_files',
        'download_files',
        'view_audit_logs',
        'export_data',
        'view_vulnerabilities',
        'create_vulnerabilities',
        'edit_vulnerabilities',
        'delete_vulnerabilities',
        'manage_users',
        'manage_settings',
        'manage_advanced_settings',
        'upload_sboms',
        'view_sboms',
        'view_readiness',
        'manage_exceptions',
        'export_compliance',
        'manage_feeds',
    ],
    'role_abilities' => [
        UserRole::ADMIN->value => [
            '*',
        ],
        UserRole::EDITOR->value => [
            'view_software',
            'create_software',
            'edit_software',
            'manage_dependencies',
            'view_versions',
            'create_versions',
            'edit_versions',
            'approve_versions',
            'view_content',
            'create_content',
            'edit_content',
            'upload_files',
            'edit_files',
            'download_files',
            'view_audit_logs',
            'export_data',
            'view_vulnerabilities',
            'create_vulnerabilities',
            'edit_vulnerabilities',
            'upload_sboms',
            'view_sboms',
            'view_readiness',
        ],
        UserRole::VIEWER->value => [
            'view_software',
            'view_versions',
            'view_content',
            'download_files',
            'view_audit_logs',
            'view_vulnerabilities',
        ],
    ],
];
